"""
monitoring/metrics.py — Prometheus metrics for the arb bot.

Exposes an HTTP /metrics endpoint (default port 8000) that Prometheus can
scrape.  All counters and histograms are module-level singletons so any part
of the codebase can import and increment them directly.

Usage:
    from monitoring.metrics import start_metrics_server, SIGNALS_GENERATED

    start_metrics_server(port=8000)
    SIGNALS_GENERATED.labels(pair="ETH/USDT").inc()
"""

from __future__ import annotations

import logging

from prometheus_client import Counter, Gauge, Histogram, start_http_server

log = logging.getLogger(__name__)

SIGNALS_GENERATED = Counter(
    "arb_signals_generated_total",
    "Total signals generated by SignalGenerator",
    ["pair"],
)

SIGNALS_SKIPPED = Counter(
    "arb_signals_skipped_total",
    "Signals skipped (below score threshold or cooldown)",
    ["pair", "reason"],
)

TRADES_EXECUTED = Counter(
    "arb_trades_executed_total",
    "Trade execution outcomes",
    ["pair", "state"],
)

CIRCUIT_BREAKER_TRIPS = Counter(
    "arb_circuit_breaker_trips_total",
    "Number of times the circuit breaker tripped",
)

UNWINDS = Counter(
    "arb_unwinds_total",
    "Number of unwind operations triggered",
    ["pair"],
)

REPLAY_BLOCKS = Counter(
    "arb_replay_blocks_total",
    "Duplicate signals blocked by replay protection",
)

CIRCUIT_BREAKER_OPEN = Gauge(
    "arb_circuit_breaker_open",
    "1 if the circuit breaker is currently open, 0 otherwise",
)

INVENTORY_BALANCE = Gauge(
    "arb_inventory_balance",
    "Current inventory balance at a venue",
    ["venue", "asset"],
)

SIGNAL_SCORE = Histogram(
    "arb_signal_score",
    "Distribution of signal scores at execution time",
    ["pair"],
    buckets=[10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
)

SPREAD_BPS = Histogram(
    "arb_spread_bps",
    "Observed spread in basis points",
    ["pair"],
    buckets=[30, 50, 75, 100, 150, 200, 300, 500],
)

PNL_USD = Histogram(
    "arb_pnl_usd",
    "Net PnL per completed trade in USD",
    ["pair"],
    buckets=[-50, -20, -10, -5, 0, 5, 10, 20, 50, 100],
)

EXECUTION_LATENCY = Histogram(
    "arb_execution_latency_seconds",
    "Wall-clock time from signal generation to execution completion",
    ["pair"],
    buckets=[0.1, 0.25, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0],
)


def start_metrics_server(port: int = 8000) -> None:
    """Start the Prometheus HTTP /metrics server on the given port."""
    start_http_server(port)
    log.info("Prometheus metrics server started on port %d", port)
